/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.csia;

import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author student
 */
// class for users to select a topic to practices or select to retrieve previous progress
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form CSIAGUI
     */
    
    private String t;   //keeps track of topic
    private char a; //stores the answer of the current question
    private int questionNumberIndex; //keeps track of question number's index
    private static QuestionForm q;
    private static QuestionGenerator gen; 
    private String pCorrect; // keeps track of user progress, specifically the number of questions he has gotten correct in the latest round
    private String pWrong; // keeps track of user progress, specifically the number of questions he has gotten wrong in the latest round
    private String pScore; // keeps track of user progress, specifically his/her score in the latest round
    private String pLevel; // keeps track of user progress, specifically his/her level in the latest round
    private String pTopic; // keeps track of user progress, specifically the latest topic practiced
    private String pQuestionNumber; // keeps track of user progress, specifically the question number of the question where he left off
    private int aQuestionNumber; // index of question to be retrieved if user wants to retrieve previous progress
    private static boolean retrieve; // boolean variable to check whether user has retrieved previous progress or is starting fresh
    private static int grz;
    
    // constructor of Home class
    public Home() 
    {
        initComponents();
        setResizable(false);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)dimension.getWidth(), (int)dimension.getHeight()); 
        t = "";
        questionNumberIndex = 0;
        pCorrect = "";
        pWrong = "";
        pScore = "";
        pLevel = "";
        pTopic = "";
        pQuestionNumber = "";
        aQuestionNumber = 0;
        retrieve = false;
        gen = null;
    }
    
    // accessor method of variable t
    public String getT()
    {
        return t;
    }
    
    // accessor method of variable a
    public char getA()
    {
        return a;
    }
    
    // accessor method of variable questionNumberindex
    public int getQuestionNumberIndex()
    {
        return questionNumberIndex;
    }
    
    // mutator method of variable questionNumberindex
    public void setA(char a)
    {
        this.a = a;
    }
    
    // mutator method of variable questionNumberindex
    public void setQuestionNumberIndex(int questionNumberIndex)
    {
        this.questionNumberIndex = questionNumberIndex;
    }
    
    // mutator method of variable retrieve
    public static void setRetrieve()
    {
        retrieve = false;
    }
    
    // accessor method of variable retrieve
    public static boolean getRetrieve()
    {
        return retrieve;
    }
    
    // accessor method of variable grz
    public static int getGRZ()
    {
        return grz;
    }
    
    // mutator method of variable grz
    public void setGRZ(int grz)
    {
        this.grz = grz;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mLevel1 = new javax.swing.JButton();
        kLevel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        wLevel1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cLevel1 = new javax.swing.JButton();
        eLevel1 = new javax.swing.JButton();
        tLevel1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jexit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setSize(new java.awt.Dimension(200, 200));

        mLevel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        mLevel1.setText("Select");
        mLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLevel1ActionPerformed(evt);
            }
        });

        kLevel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        kLevel1.setText("Select");
        kLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kLevel1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Kinematics");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Measurement and Uncertainties");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Waves and Simple Harmonic Motion");

        wLevel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        wLevel1.setText("Select");
        wLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wLevel1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Circular Motion and Gravitation");

        cLevel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        cLevel1.setText("Select");
        cLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLevel1ActionPerformed(evt);
            }
        });

        eLevel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        eLevel1.setText("Select");
        eLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLevel1ActionPerformed(evt);
            }
        });

        tLevel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        tLevel1.setText("Select");
        tLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLevel1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Electricity and Magnetism");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Thermal Physics");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel8.setText("Welcome to the ultimate IB Physics revision tool!");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 2, 25)); // NOI18N
        jLabel9.setText("To start, please select a topic below to practice or select \"Retrieve Progress\" to continue");

        jexit.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton1.setText("Retrieve Progress");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 2, 25)); // NOI18N
        jLabel10.setText("your previous progress.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(286, 286, 286)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tLevel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(33, 33, 33)
                                        .addComponent(jexit))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mLevel1)
                                            .addComponent(kLevel1)
                                            .addComponent(wLevel1)
                                            .addComponent(cLevel1)
                                            .addComponent(eLevel1))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mLevel1))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kLevel1))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wLevel1))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cLevel1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLevel1)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLevel1)
                    .addComponent(jexit)
                    .addComponent(jButton1)
                    .addComponent(jLabel7))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 51)); // NOI18N
        jLabel1.setText("IB Physics Practice Tool");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel11.setText("Question Sources: IBDP Physics Higher Level Examination Paper 1&2 2014-2017; Oxford IB Diploma Programme Physics Course Companion by Homer, David, and Michael Brown-Jones;");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel12.setText("All copyrighted materials belong to their respective copyright owners. This application and its users agree to abide by the copyright owners' rules and policy for use of intellectual property.");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jLabel13.setText("Physics for the IB Diploma ​by K. A. Tsokos; and Grade Gorilla IB Physics Questions. This application is to be used for educational purposes only. ");

        jButton3.setText("View Detailed Sources");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(94, 94, 94))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kLevel1ActionPerformed
        // sets up questions of the topic "kinematics"
        setVisible(false);
        t = "k"; 
        q = new QuestionForm();
        q.setVisible(true);   
        q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
        q.groupButtons();
        q.setSTopic("k");
        q.wrap();
        gen = new QuestionGenerator();
        gen.setFileName("kinematics.txt"); 
        gen.storeQuestion();
        qSetUp("k", 0);
    }//GEN-LAST:event_kLevel1ActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        // exits the program
        System.exit(0);
    }//GEN-LAST:event_jexitActionPerformed

    private void mLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLevel1ActionPerformed
        // sets up questions fo the topic "measurement and uncertainties"
        setVisible(false);
        t = "mu"; 
        q = new QuestionForm();
        q.setVisible(true);   
        q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
        q.groupButtons();
        q.setSTopic("mu");
        q.wrap();
        gen = new QuestionGenerator();
        gen.setFileName("measurement and uncertainties.txt"); 
        gen.storeQuestion();
        qSetUp("mu", 0);  // use of sub-procedure
    }//GEN-LAST:event_mLevel1ActionPerformed

    private void wLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wLevel1ActionPerformed
        // sets up questions of the topic "waves and shm"
        setVisible(false);
        t = "w"; 
        q = new QuestionForm();
        q.setVisible(true);   
        q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
        q.groupButtons();
        q.setSTopic("w");
        q.wrap();
        gen = new QuestionGenerator();
        gen.setFileName("waves and shm.txt"); 
        gen.storeQuestion();
        qSetUp("w", 0); 
    }//GEN-LAST:event_wLevel1ActionPerformed

    private void cLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLevel1ActionPerformed
        // sets up questions from the topic "cirular motion"
        setVisible(false);
        t = "c";
        q = new QuestionForm();
        q.setVisible(true);   
        q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
        q.groupButtons();
        q.setSTopic("c");
        q.wrap();
        gen = new QuestionGenerator();
        gen.setFileName("circular motion.txt"); 
        gen.storeQuestion();
        qSetUp("c", 0); 
    }//GEN-LAST:event_cLevel1ActionPerformed

    private void eLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLevel1ActionPerformed
        //sets up questions of the topic "electricity and magnetism"
        setVisible(false);
        t = "em"; 
        q = new QuestionForm();
        q.setVisible(true);   
        q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
        q.groupButtons();
        q.setSTopic("em");
        q.wrap();
        gen = new QuestionGenerator();
        gen.setFileName("electricity and magnetism.txt"); 
        gen.storeQuestion();
        qSetUp("em", 0); 
    }//GEN-LAST:event_eLevel1ActionPerformed

    private void tLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLevel1ActionPerformed
        // sets up all questions of the topic "thermal physics"
        setVisible(false);
        t = "t"; 
        q = new QuestionForm();
        q.setVisible(true);   
        q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
        q.groupButtons();
        q.setSTopic("t");
        q.wrap();
        gen = new QuestionGenerator();
        gen.setFileName("thermal physics.txt"); 
        gen.storeQuestion();
        qSetUp("t", 0); 
    }//GEN-LAST:event_tLevel1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // retrieve score, right, wrong, level, and question number from text file
        try
        {
            FileReader fileReader = new FileReader("User Progress.txt");
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            StringBuilder numberCorrect = new StringBuilder();
            StringBuilder numberWrong = new StringBuilder();
            StringBuilder score = new StringBuilder();
            StringBuilder level = new StringBuilder();
            StringBuilder topic = new StringBuilder();
            StringBuilder questionNumber = new StringBuilder();
            StringBuilder capture = new StringBuilder();
            String line;
            
            if ((line = bufferedReader.readLine()) != null)
            {
                pCorrect = numberCorrect.append(line).toString();
            }
            
            if ((line = bufferedReader.readLine()) != null)
            {
                pWrong = numberWrong.append(line).toString();
            }
            
            if ((line = bufferedReader.readLine()) != null)
            {
                pScore = score.append(line).toString();
            }
            
            if ((line = bufferedReader.readLine()) != null)
            {
                pLevel = level.append(line).toString();
            }
            
            if ((line = bufferedReader.readLine()) != null)
            {
                pTopic = topic.append(line).toString();
            }
            
            if ((line = bufferedReader.readLine()) != null)
            { 
                pQuestionNumber = questionNumber.append(line).toString();
            }
           
        }
        // exception handling
        catch(FileNotFoundException ex) 
        {
            System.out.println("Sorry, unable to open file '" + "User Progress.txt" + "'");                
        }
        catch(IOException ex) 
        {
            System.out.println("Error reading file '" + "User Progress.txt" + "'"); 
        } 
        int e = -1;
        int f = -1;
        if (pCorrect.equalsIgnoreCase("c") == false)
        {
            e = Integer.parseInt(pCorrect);
            f = Integer.parseInt(pWrong); 
        }
        if(((e + f)==0)|| (pTopic.equals("")))
        {
            JOptionPane.showMessageDialog(null, "User progress unavailable; the user did not attempt any questions in the most recent round or did not choose to save his most recent progress.", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (pCorrect.toString().equalsIgnoreCase("c"))
        {
            JOptionPane.showMessageDialog(null, "User progress unavailable; the user has completed all questions of the topic attempted in the most recent round.", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            int qN = Integer.parseInt(pQuestionNumber);
            aQuestionNumber = qN - 1;
            q = new QuestionForm();
            q.setVisible(true);
            setVisible(false);
            q.setVisible(true);   
            q.setUneditable(); //set counter textfield and question textarea as uneditable, but still able to copy content
            q.groupButtons();
            q.wrap();
            q.setSTopic(pTopic);
            gen = new QuestionGenerator();
            gen.setFileName(q.getFile(pTopic));  
            gen.storeQuestion();
            q.getJ1().setText(pCorrect);
            q.getJ2().setText(pWrong);
            q.getJ3().setText(pScore);
            q.getJ4().setText(pLevel);
        
            q.getTextArea().setText(gen.getQuestionText(pTopic,aQuestionNumber)); 
            q.getb1().setText(gen.getAnswerOptions(pTopic, aQuestionNumber, 0));
            q.getb2().setText(gen.getAnswerOptions(pTopic, aQuestionNumber, 1));
            q.getb3().setText(gen.getAnswerOptions(pTopic, aQuestionNumber, 2));
            q.getb4().setText(gen.getAnswerOptions(pTopic, aQuestionNumber, 3));
            q.setA(gen.getAns(pTopic, aQuestionNumber).charAt(0));
            grz = qN;
        }
        retrieve = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // displays citations of questions used by this program
        Citations citations = new Citations();
        citations.setVisible(true);
        citations.getA().setEditable(false);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
  
    // displays the question and answer options of a question, and sets the correct answer of a question of specified topic and question number
    public static void qSetUp(String topic, int questionNumberIndex2)
    {
        q.getTextArea().setText(gen.getQuestionText(topic,questionNumberIndex2)); // q is null and topic is empty
        q.getb1().setText(gen.getAnswerOptions(topic, questionNumberIndex2, 0));
        q.getb2().setText(gen.getAnswerOptions(topic, questionNumberIndex2, 1));
        q.getb3().setText(gen.getAnswerOptions(topic, questionNumberIndex2, 2));
        q.getb4().setText(gen.getAnswerOptions(topic, questionNumberIndex2, 3));
        q.setA(gen.getAns(topic, questionNumberIndex2).charAt(0));

    }
    
    public QuestionForm getQ()
    {
        return q; 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cLevel1;
    private javax.swing.JButton eLevel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jexit;
    private javax.swing.JButton kLevel1;
    private javax.swing.JButton mLevel1;
    private javax.swing.JButton tLevel1;
    private javax.swing.JButton wLevel1;
    // End of variables declaration//GEN-END:variables
}
